Correcting clearly wrong package names in test that cause failure on Eclair
Guess they changed the resolution algorithm for post 2.1...

java.lang.RuntimeException: Unable to resolve activity for: Intent { act=org.openintents.git.tag.LIST flg=0x10000000 cmp=com.agit/com.madgag.agit.RDTypeListActivity (has extras) }
	at android.app.Instrumentation.startActivitySync(Instrumentation.java:371)
	at android.test.InstrumentationTestCase.launchActivityWithIntent(InstrumentationTestCase.java:120)
	at android.test.ActivityInstrumentationTestCase2.getActivity(ActivityInstrumentationTestCase2.java:89)
	at com.madgag.agit.RDTypeListActivityStoryTest.testShouldShowAllTags(RDTypeListActivityStoryTest.java:62)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:205)
	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:195)
	at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:175)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:430)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1447)